// Dylan Archer Dingwell
// BEMATHMR is a magnetic resonance module for the Smoldyn biochemical simulation platform.
// bemathmr.h is the header file for BEMATHMR.

#ifndef __bemathmr_h__
#define __bemathmr_h__

#include <string.h>
#include "smoldyn.h"                    // Smoldyn header
#include "smoldynfuncs.h"               // Smoldyn functions header
#include "smoldynconfigure.h"			// Smoldyn configuration header, generated by CMake from smoldynconfigure.h.in

/** BEMATHMR wrappers for Smoldyn structures. **/

typedef struct bemathmrblockstruct {
	moleculeptr *smolmptr;              // pointer to molecule in Smoldyn
	int spinspecies;                    // species of spin
	double gyromag;                     // gyromagnetic ratio
	double Mx;                     // Mx
	double My;                     // My
	double Mz;                     // Mz
} *bemathmrblockptr;
	
typedef struct bemathmrblocksuperstruct {
	molsuperstruct *bemathmrmolss;           // Smoldyn molecule superstructure
} *bemathmrblocksuperptr;

void bemathmr_timestep();
double vecmag(double v0, double v1, double v2);
double hp0(double q0, double q1, double q2, double q3, double p0, double p1, double p2, double p3);
double hp1(double q0, double q1, double q2, double q3, double p0, double p1, double p2, double p3);
double hp2(double q0, double q1, double q2, double q3, double p0, double p1, double p2, double p3);
double hp3(double q0, double q1, double q2, double q3, double p0, double p1, double p2, double p3);
void rotquat(double gamma, double tau, double &mx, double &my, double &mz, double &bx, double &by, double &bz);

#endif